[build]
  # Since this is a static site with no build process, we don't need a build command
  publish = "."

# Optional: Configure redirects for SPA if needed in the future
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Configure headers for security and caching
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
